# Generated by Django 4.1.2 on 2022-10-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Summary'),
        ),
    ]
