# Generated by Django 4.1.2 on 2022-10-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_tasks_description_alter_tasks_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='type',
        ),
        migrations.AddField(
            model_name='tasks',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='todolist.type', verbose_name='Тип задачи'),
        ),
    ]
